services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./eat.db:/app/eat.db
      - ./img:/app/img
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

        #  cloudflared:
        #    image: cloudflare/cloudflared:latest
        #    network_mode: host
        #    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN:?set tunnel token in env}
        #    depends_on:
        #      - app
        #    restart: unless-stopped
